-- Migración: Engadir textos "Sobre nós" á configuración
-- Executar só se a BD xa existe e os campos están en NULL

UPDATE `config` SET
  `sobre_nos_gl` = 'A Levada Arraiana é un grupo de batucada con sede en Estás, Tomiño (Pontevedra), na fronteira entre Galicia e Portugal. Nacemos da paixón polo ritmo e pola cultura de percusión brasileira, adaptándoa ao noso contexto galego.\n\nOs nosos instrumentos — surdos, caixas, repiniques, tamborins, agogôs, ganzás e apitos — crean unha enerxía colectiva que fai vibrar rúas, festas e festivais. Ensaiamos regularmente para manter un repertorio vivo e en constante evolución.\n\nSe che gusta a percusión e queres formar parte dunha comunidade musical aberta e participativa, a Levada Arraiana agárdache. Non precisas experiencia previa — só ganas de tocar!',
  `sobre_nos_es` = 'Levada Arraiana es un grupo de batucada con sede en Estás, Tomiño (Pontevedra), en la frontera entre Galicia y Portugal. Nacimos de la pasión por el ritmo y por la cultura de percusión brasileña, adaptándola a nuestro contexto gallego.\n\nNuestros instrumentos — surdos, cajas, repiniques, tamborines, agogôs, ganzás y apitos — crean una energía colectiva que hace vibrar calles, fiestas y festivales. Ensayamos regularmente para mantener un repertorio vivo y en constante evolución.\n\nSi te gusta la percusión y quieres formar parte de una comunidad musical abierta y participativa, Levada Arraiana te espera. No necesitas experiencia previa — ¡solo ganas de tocar!',
  `sobre_nos_pt` = 'A Levada Arraiana é um grupo de batucada com sede em Estás, Tomiño (Pontevedra), na fronteira entre a Galiza e Portugal. Nascemos da paixão pelo ritmo e pela cultura de percussão brasileira, adaptando-a ao nosso contexto galego.\n\nOs nossos instrumentos — surdos, caixas, repiniques, tamborins, agogôs, ganzás e apitos — criam uma energia coletiva que faz vibrar ruas, festas e festivais. Ensaiamos regularmente para manter um repertório vivo e em constante evolução.\n\nSe gostas de percussão e queres fazer parte de uma comunidade musical aberta e participativa, a Levada Arraiana espera por ti. Não precisas de experiência prévia — só vontade de tocar!',
  `sobre_nos_en` = 'Levada Arraiana is a batucada group based in Estás, Tomiño (Pontevedra), on the border between Galicia and Portugal. We were born from a passion for rhythm and Brazilian percussion culture, adapting it to our Galician context.\n\nOur instruments — surdos, snare drums, repiniques, tamborims, agogôs, ganzás and whistles — create a collective energy that makes streets, festivals and celebrations come alive. We rehearse regularly to keep our repertoire fresh and constantly evolving.\n\nIf you love percussion and want to be part of an open and participatory musical community, Levada Arraiana is waiting for you. No previous experience needed — just the desire to play!'
WHERE `id` = 1 AND `sobre_nos_gl` IS NULL;
